require("phivert.plugins.treesitter")
require("phivert.plugins.theme")
require("phivert.plugins.autopairs")
require("phivert.plugins.texplorer")
require("phivert.plugins.ibl")
require("phivert.plugins.nvterm")
require("phivert.plugins.lspconfig")
