require("after.plugin.colors")
require("after.plugin.fugitive")
require("after.plugin.lsp")
require("after.plugin.neodev")
require("after.plugin.nvimtree")
require("after.plugin.nvterm")
require("after.plugin.telescope")
require("after.plugin.undotree")

require("after.plugin.dap.bashdb")
require("after.plugin.dap.dap")
require("after.plugin.dap.keymaps")
require("after.plugin.dap.python")
require("after.plugin.dap.ui")
require("after.plugin.dap.virtual-text")
